import type { Exercise } from "@/types/workout";

// Seed content — a representative library across all six PRD-003
// categories, not an exhaustive database. Structured so more exercises
// can be appended without touching any engine logic below.
export const EXERCISE_LIBRARY: Exercise[] = [
  // ---- Cardio ----
  {
    id: "c-walk",
    name: "Wandelen",
    category: "cardio",
    description: "Rustig tempo wandelen, buiten of op de loopband.",
    animation_ref: "walk-basic",
    equipment_required: [],
    difficulty: "beginner",
    prescription_type: "duration",
    base_target: 600, // seconds
    base_sets: 1,
    estimated_duration_min: 10,
    target_muscle_groups: ["benen", "cardiovasculair"],
    target_skills: ["uithoudingsvermogen"],
    safety_instructions: "Houd een tempo aan waarbij je nog kunt praten.",
    alternative_exercise_id: "c-bike",
    high_impact: false,
  },
  {
    id: "c-interval-walk",
    name: "Interval wandelen",
    category: "cardio",
    description: "Afwisselend 1 minuut stevig doorstappen, 2 minuten rustig.",
    animation_ref: "interval-walk",
    equipment_required: [],
    difficulty: "gemiddeld",
    prescription_type: "duration",
    base_target: 900,
    base_sets: 1,
    estimated_duration_min: 15,
    target_muscle_groups: ["benen", "cardiovasculair"],
    target_skills: ["uithoudingsvermogen"],
    safety_instructions: "Bouw de stevige stukken rustig op, forceer niet.",
    alternative_exercise_id: "c-walk",
    high_impact: false,
  },
  {
    id: "c-run",
    name: "Hardlopen",
    category: "cardio",
    description: "Duurloop in rustig tempo.",
    animation_ref: "run-basic",
    equipment_required: [],
    difficulty: "gevorderd",
    prescription_type: "duration",
    base_target: 900,
    base_sets: 1,
    estimated_duration_min: 15,
    target_muscle_groups: ["benen", "cardiovasculair"],
    target_skills: ["uithoudingsvermogen", "Harbor Run readiness"],
    safety_instructions: "Stop direct bij hielpijn of scherpe pijn in de voet.",
    alternative_exercise_id: "c-interval-walk",
    high_impact: true,
  },
  {
    id: "c-bike",
    name: "Fietsen",
    category: "cardio",
    description: "Rustige tot stevige fietstraining.",
    animation_ref: "cycling-basic",
    equipment_required: ["Hometrainer"],
    difficulty: "beginner",
    prescription_type: "duration",
    base_target: 900,
    base_sets: 1,
    estimated_duration_min: 15,
    target_muscle_groups: ["benen", "cardiovasculair"],
    target_skills: ["uithoudingsvermogen"],
    safety_instructions: "Zadelhoogte zo dat de knie licht gebogen blijft onderaan.",
    alternative_exercise_id: "c-walk",
    high_impact: false,
  },
  {
    id: "c-aqua",
    name: "Aquafitness",
    category: "cardio",
    description: "Cardiotraining in het water — al gewichtdragend, maar zacht voor de gewrichten.",
    animation_ref: "aqua-basic",
    equipment_required: ["Zwembad"],
    difficulty: "beginner",
    prescription_type: "duration",
    base_target: 2700,
    base_sets: 1,
    estimated_duration_min: 45,
    target_muscle_groups: ["hele lichaam", "cardiovasculair"],
    target_skills: ["uithoudingsvermogen"],
    safety_instructions: "Uitstekende optie bij voetklachten — het water draagt het gewicht.",
    alternative_exercise_id: "c-bike",
    high_impact: false,
  },

  // ---- Strength ----
  {
    id: "s-squat",
    name: "Squats",
    category: "strength",
    description: "Bodyweight squat, rug recht, knieën in lijn met de tenen.",
    animation_ref: "squat-basic",
    equipment_required: [],
    difficulty: "beginner",
    prescription_type: "reps",
    base_target: 10,
    base_sets: 3,
    estimated_duration_min: 5,
    target_muscle_groups: ["benen", "billen"],
    target_skills: ["kracht"],
    safety_instructions: "Zak niet dieper dan comfortabel is voor de knieën.",
    alternative_exercise_id: "s-glute-bridge",
    high_impact: false,
  },
  {
    id: "s-pushup",
    name: "Push-ups",
    category: "strength",
    description: "Op de knieën of volledig, borst richting de grond.",
    animation_ref: "pushup-basic",
    equipment_required: [],
    difficulty: "gemiddeld",
    prescription_type: "reps",
    base_target: 8,
    base_sets: 3,
    estimated_duration_min: 5,
    target_muscle_groups: ["borst", "armen", "core"],
    target_skills: ["kracht"],
    safety_instructions: "Houd de core aangespannen, laat de heupen niet zakken.",
    alternative_exercise_id: "s-band-row",
    high_impact: false,
  },
  {
    id: "s-dumbbell-row",
    name: "Dumbbell rows",
    category: "strength",
    description: "Roeibeweging met dumbbells, rug neutraal.",
    animation_ref: "db-row-basic",
    equipment_required: ["Dumbbells"],
    difficulty: "gemiddeld",
    prescription_type: "reps",
    base_target: 10,
    base_sets: 3,
    estimated_duration_min: 5,
    target_muscle_groups: ["rug", "armen"],
    target_skills: ["kracht"],
    safety_instructions: "Beweeg gecontroleerd, geen zwaai vanuit de rug.",
    alternative_exercise_id: "s-band-row",
    high_impact: false,
  },
  {
    id: "s-band-row",
    name: "Weerstandsband rows",
    category: "strength",
    description: "Roeibeweging met een weerstandsband, zittend of staand.",
    animation_ref: "band-row-basic",
    equipment_required: ["Weerstandsbanden"],
    difficulty: "beginner",
    prescription_type: "reps",
    base_target: 12,
    base_sets: 3,
    estimated_duration_min: 5,
    target_muscle_groups: ["rug", "armen"],
    target_skills: ["kracht"],
    safety_instructions: "Volledig zittend uit te voeren — belast de voet niet.",
    alternative_exercise_id: null,
    high_impact: false,
  },
  {
    id: "s-glute-bridge",
    name: "Glute bridges",
    category: "strength",
    description: "Liggend, heupen omhoog duwen, billen aanspannen.",
    animation_ref: "glute-bridge-basic",
    equipment_required: [],
    difficulty: "beginner",
    prescription_type: "reps",
    base_target: 12,
    base_sets: 3,
    estimated_duration_min: 5,
    target_muscle_groups: ["billen", "hamstrings", "core"],
    target_skills: ["kracht"],
    safety_instructions: "Geen gewicht door de hiel bij opdrukken nodig — druk via de hele voet.",
    alternative_exercise_id: null,
    high_impact: false,
  },

  // ---- Mobility ----
  {
    id: "m-catcow",
    name: "Cat-cow stretch",
    category: "mobility",
    description: "Op handen en knieën, rug afwisselend welven en hollen.",
    animation_ref: "catcow-basic",
    equipment_required: ["Yogamat"],
    difficulty: "beginner",
    prescription_type: "duration",
    base_target: 60,
    base_sets: 2,
    estimated_duration_min: 3,
    target_muscle_groups: ["rug", "core"],
    target_skills: ["mobiliteit"],
    safety_instructions: "Beweeg langzaam mee met de ademhaling.",
    alternative_exercise_id: null,
    high_impact: false,
  },
  {
    id: "m-hip-opener",
    name: "Heupopeners",
    category: "mobility",
    description: "Zittende of liggende heupmobiliteit.",
    animation_ref: "hip-opener-basic",
    equipment_required: ["Yogamat"],
    difficulty: "beginner",
    prescription_type: "duration",
    base_target: 60,
    base_sets: 2,
    estimated_duration_min: 3,
    target_muscle_groups: ["heupen"],
    target_skills: ["mobiliteit"],
    safety_instructions: "Forceer nooit door pijn heen.",
    alternative_exercise_id: null,
    high_impact: false,
  },
  {
    id: "m-ankle-circles",
    name: "Enkelcirkels",
    category: "mobility",
    description: "Rustige cirkelbewegingen met de enkel, zittend.",
    animation_ref: "ankle-circles-basic",
    equipment_required: [],
    difficulty: "beginner",
    prescription_type: "reps",
    base_target: 10,
    base_sets: 2,
    estimated_duration_min: 2,
    target_muscle_groups: ["enkel"],
    target_skills: ["mobiliteit"],
    safety_instructions: "Volledig zittend, geen gewicht op de voet — geschikt bij hielklachten.",
    alternative_exercise_id: null,
    high_impact: false,
  },
  {
    id: "m-shoulder-flow",
    name: "Schoudermobiliteit flow",
    category: "mobility",
    description: "Armcirkels en schouderrollen.",
    animation_ref: "shoulder-flow-basic",
    equipment_required: [],
    difficulty: "beginner",
    prescription_type: "duration",
    base_target: 60,
    base_sets: 2,
    estimated_duration_min: 3,
    target_muscle_groups: ["schouders"],
    target_skills: ["mobiliteit"],
    safety_instructions: "Rustige, gecontroleerde bewegingen.",
    alternative_exercise_id: null,
    high_impact: false,
  },

  // ---- Recovery ----
  {
    id: "r-breathing",
    name: "Ademhalingsoefening",
    category: "recovery",
    description: "4-7-8 ademhaling, zittend of liggend.",
    animation_ref: "breathing-basic",
    equipment_required: [],
    difficulty: "beginner",
    prescription_type: "duration",
    base_target: 300,
    base_sets: 1,
    estimated_duration_min: 5,
    target_muscle_groups: [],
    target_skills: ["herstel"],
    safety_instructions: "Geschikt voor elke dag, ook op rustdagen.",
    alternative_exercise_id: null,
    high_impact: false,
  },
  {
    id: "r-recovery-walk",
    name: "Herstelwandeling",
    category: "recovery",
    description: "Zeer rustige korte wandeling.",
    animation_ref: "recovery-walk",
    equipment_required: [],
    difficulty: "beginner",
    prescription_type: "duration",
    base_target: 600,
    base_sets: 1,
    estimated_duration_min: 10,
    target_muscle_groups: ["benen"],
    target_skills: ["herstel"],
    safety_instructions: "Stop bij toenemende voetpijn.",
    alternative_exercise_id: "r-breathing",
    high_impact: false,
  },
  {
    id: "r-foam-roll",
    name: "Foam rolling",
    category: "recovery",
    description: "Zelfmassage van kuiten, quadriceps en rug.",
    animation_ref: "foam-roll-basic",
    equipment_required: ["Anders"],
    difficulty: "beginner",
    prescription_type: "duration",
    base_target: 300,
    base_sets: 1,
    estimated_duration_min: 5,
    target_muscle_groups: ["benen", "rug"],
    target_skills: ["herstel"],
    safety_instructions: "Vermijd direct over de pijnlijke hiel te rollen.",
    alternative_exercise_id: "r-breathing",
    high_impact: false,
  },
  {
    id: "r-relaxation",
    name: "Ontspanningsoefening",
    category: "recovery",
    description: "Progressieve spierontspanning, liggend.",
    animation_ref: "relaxation-basic",
    equipment_required: ["Yogamat"],
    difficulty: "beginner",
    prescription_type: "duration",
    base_target: 300,
    base_sets: 1,
    estimated_duration_min: 5,
    target_muscle_groups: [],
    target_skills: ["herstel"],
    safety_instructions: "Geen fysieke belasting — geschikt op elke dag.",
    alternative_exercise_id: null,
    high_impact: false,
  },

  // ---- Injury prevention ----
  {
    id: "ip-ankle-stability",
    name: "Enkelstabiliteit",
    category: "injury_prevention",
    description: "Eenbenig balanceren met lichte enkelbeweging.",
    animation_ref: "ankle-stability-basic",
    equipment_required: [],
    difficulty: "beginner",
    prescription_type: "duration",
    base_target: 30,
    base_sets: 3,
    estimated_duration_min: 3,
    target_muscle_groups: ["enkel", "kuit"],
    target_skills: ["stabiliteit", "Harbor Run readiness"],
    safety_instructions: "Op het niet-geblesseerde been uitvoeren indien de andere voet pijnlijk is.",
    alternative_exercise_id: "m-ankle-circles",
    high_impact: false,
  },
  {
    id: "ip-knee-stability",
    name: "Kniestabiliteit",
    category: "injury_prevention",
    description: "Gecontroleerde step-downs op een lage opstap.",
    animation_ref: "knee-stability-basic",
    equipment_required: [],
    difficulty: "gemiddeld",
    prescription_type: "reps",
    base_target: 8,
    base_sets: 2,
    estimated_duration_min: 4,
    target_muscle_groups: ["knie", "benen"],
    target_skills: ["stabiliteit"],
    safety_instructions: "Zeer laag tempo, knie blijft in lijn met de voet.",
    alternative_exercise_id: "s-glute-bridge",
    high_impact: false,
  },
  {
    id: "ip-hip-stability",
    name: "Heupstabiliteit",
    category: "injury_prevention",
    description: "Zijwaartse beenheffingen, liggend.",
    animation_ref: "hip-stability-basic",
    equipment_required: [],
    difficulty: "beginner",
    prescription_type: "reps",
    base_target: 12,
    base_sets: 2,
    estimated_duration_min: 4,
    target_muscle_groups: ["heupen", "billen"],
    target_skills: ["stabiliteit"],
    safety_instructions: "Volledig liggend, geen belasting door de voet.",
    alternative_exercise_id: null,
    high_impact: false,
  },
  {
    id: "ip-shoulder-mobility",
    name: "Schoudermobiliteit (preventie)",
    category: "injury_prevention",
    description: "Wandvingerlopen en schouder-CARs.",
    animation_ref: "shoulder-mobility-prevent",
    equipment_required: [],
    difficulty: "beginner",
    prescription_type: "duration",
    base_target: 60,
    base_sets: 2,
    estimated_duration_min: 3,
    target_muscle_groups: ["schouders"],
    target_skills: ["stabiliteit"],
    safety_instructions: "Rustig tempo, stop bij scherpe pijn.",
    alternative_exercise_id: "m-shoulder-flow",
    high_impact: false,
  },

  // ---- Harbor Run skills ----
  {
    id: "hr-grip",
    name: "Grip kracht",
    category: "harbor_run_skills",
    description: "Vasthouden aan een stang of handdoek, dead hang variant.",
    animation_ref: "grip-strength-basic",
    equipment_required: [],
    difficulty: "gemiddeld",
    prescription_type: "duration",
    base_target: 20,
    base_sets: 3,
    estimated_duration_min: 4,
    target_muscle_groups: ["onderarmen", "grip"],
    target_skills: ["Harbor Run readiness"],
    safety_instructions: "Bouw de tijd rustig op, laat direct los bij pijn in pols of hand.",
    alternative_exercise_id: null,
    high_impact: false,
  },
  {
    id: "hr-crawl",
    name: "Kruipen",
    category: "harbor_run_skills",
    description: "Berenkruip patroon, handen en voeten op de grond.",
    animation_ref: "crawl-basic",
    equipment_required: [],
    difficulty: "gemiddeld",
    prescription_type: "duration",
    base_target: 60,
    base_sets: 3,
    estimated_duration_min: 5,
    target_muscle_groups: ["core", "schouders", "benen"],
    target_skills: ["Harbor Run readiness", "obstakel voorbereiding"],
    safety_instructions: "Belast de voet gedeeltelijk — bij hielpijn vervangen door alternatief.",
    alternative_exercise_id: "hr-core-plank",
    high_impact: true,
  },
  {
    id: "hr-carry",
    name: "Dragen (farmer's carry)",
    category: "harbor_run_skills",
    description: "Lopen met een gewicht in elke hand, rechte houding.",
    animation_ref: "farmers-carry-basic",
    equipment_required: ["Dumbbells"],
    difficulty: "gemiddeld",
    prescription_type: "duration",
    base_target: 40,
    base_sets: 3,
    estimated_duration_min: 5,
    target_muscle_groups: ["grip", "core", "benen"],
    target_skills: ["Harbor Run readiness"],
    safety_instructions: "Kies een gewicht waarbij de houding rechtop blijft.",
    alternative_exercise_id: "hr-grip",
    high_impact: true,
  },
  {
    id: "hr-balance",
    name: "Balans",
    category: "harbor_run_skills",
    description: "Eenbenig balanceren, evt. op instabiel oppervlak.",
    animation_ref: "balance-basic",
    equipment_required: [],
    difficulty: "beginner",
    prescription_type: "duration",
    base_target: 30,
    base_sets: 3,
    estimated_duration_min: 3,
    target_muscle_groups: ["enkel", "core"],
    target_skills: ["Harbor Run readiness", "stabiliteit"],
    safety_instructions: "Sta in de buurt van een muur of stoel om vast te houden indien nodig.",
    alternative_exercise_id: "ip-ankle-stability",
    high_impact: false,
  },
  {
    id: "hr-core-plank",
    name: "Core stabiliteit (plank)",
    category: "harbor_run_skills",
    description: "Onderarmplank, rechte lijn van hoofd tot hielen.",
    animation_ref: "plank-basic",
    equipment_required: [],
    difficulty: "gemiddeld",
    prescription_type: "duration",
    base_target: 30,
    base_sets: 3,
    estimated_duration_min: 4,
    target_muscle_groups: ["core"],
    target_skills: ["Harbor Run readiness"],
    safety_instructions: "Volledig op de onderarmen — geen gewicht op de hielen.",
    alternative_exercise_id: null,
    high_impact: false,
  },
  {
    id: "hr-obstacle-prep",
    name: "Obstakel voorbereiding",
    category: "harbor_run_skills",
    description: "Box step-overs en lage wandklim-drills.",
    animation_ref: "obstacle-prep-basic",
    equipment_required: [],
    difficulty: "gevorderd",
    prescription_type: "reps",
    base_target: 8,
    base_sets: 3,
    estimated_duration_min: 6,
    target_muscle_groups: ["hele lichaam"],
    target_skills: ["Harbor Run readiness", "obstakel voorbereiding"],
    safety_instructions: "Alleen bij vrijgave voor hoge belasting — stevige landing vereist.",
    alternative_exercise_id: "hr-balance",
    high_impact: true,
  },
];

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISE_LIBRARY.find((e) => e.id === id);
}
